find broken job:"cd $JJNL\nll -rt *"
search for broken job:"cd $JJNL\nll -rt *"
run production fix:"runsql / $DAT/production_fixes.sql 0 0 "
run Friday script:"runsql / $DAT/Friday_production_script.sql"
run Friday production:"runsql / $DAT/Friday_production_script.sql"
run Friday production script:"runsql / $DAT/Friday_production_script.sql"
day to check ms:"cd /soc/hms/res \nll -rt BAL008.lst* \n"
select from Friday claims:'select * from ops$shared.caud_claims;'
now limit claim:"Claim assistance with null limit claim\nGood morning,\nPlease can you assist with the following null limit claims that are causing a failure:"
select from claim:"SELECT claim_no,contract,ino,practice,policy,serv_date,dis,state,status,limit,paycode1,paycode2,benefit_area,batch,input_id\nFROM SHARED.clm@sad WHERE claim_no in();"
